image:
  file: .gitpod.Dockerfile

tasks:
  - name: build
    init: . $HOME/esp/esp-idf/export.sh
    command: |
      idf.py menuconfig
  - name: esp-tool
    command: npx --yes serve esp-web-flash
    openMode: tab-before

ports:
  - name: esp-tool
    description: ESP Tool
    port: 3000
    onOpen: open-browser