name: Create Firmware for ESP32
run-name: ${{ github.actor }} creates the firmware 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: cache-esp-idf
      uses: actions/cache@v3
      with:
        path: ~/esp
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: setup-esp-idf
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        sudo apt-get clean autoclean
        sudo apt-get autoremove --yes
        sudo rm -rf /var/lib/{apt,dpkg,cache,log}/
        mkdir -p ~/esp
        cd ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        ./install.sh esp32
        ./install.sh esp32s2
        sudo rm -rf ~/esp/esp-idf/docs
        sudo rm -rf ~/esp/esp-idf/examples
    - name: build-firmware
      run: |
        idf.py build
